# Generated by Django 5.1.2 on 2024-11-04 13:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Имя покупателя')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Баланс')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название игры')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('size', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер файлов (ГБ)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('age_limited', models.BooleanField(default=False, verbose_name='Возрастное ограничение 18+')),
                ('buyers', models.ManyToManyField(related_name='games', to='task.buyer', verbose_name='Покупатели')),
            ],
        ),
    ]
